# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  mail: '$(git mail)'
  name: '$(git name)'
  currentBranch: '$(Build.SourceBranchName)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout and persist credential'
  persistCredentials: true

- script: git checkout $(currentBranch)
  displayName: checkout

- script: git remote add official https://github.com/tootsuite/mastodon
  displayName: add remote source

- script: git fetch official
  displayName: fetch tootsuite/mastodon

- script: git merge official/master
  displayName: merge tootsuite/mastodon:master

- script: |
          git add .
          git commit -m updated
          git push
  displayName: push