default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
witches-town: styles/witches-town.scss
neoncity: styles/neon-city.scss 
cybre-light: styles/cybre-light.scss
win95: styles/win95.scss